### ISSUE TITLE
gfx.h not found

### ISSUE THREAD

**Issue by MamaTierra** [InfiniteYuan1/esp32-ugfx-gui#4]
Hello Yuan,

I'm trying to use your example but some troubles happened during compilation : 

_C:/msys32/home/XXX/esp/ugfx_example/components/gdrivers/gdisp/framebuffer/gdisp_lld_framebuffer.c:15:17: fatal error: gfx.h: No such file or directory_

Maybe I didn't add components path correctly ...

There is my makefile : 
```
#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ugfx_example
#If UGFX_COMPONENT_PATH is not defined, use relative path as default value
UGFX_COMPONENT_PATH ?= $(abspath $(shell pwd)/)
EXTRA_COMPONENT_DIRS := $(abspath components)
 
include $(UGFX_COMPONENT_PATH)/components/component_conf.mk
include $(IDF_PATH)/make/project.mk
```

**Comment by InfiniteYuan** [comment]
Firstly, you should sure example in reposity can run correctly.
The path of components is according to your   structure of project, and you can refer to my makefile and structure.

**Comment by MamaTierra** [comment]
There is an other problem : the file "gfx.h" doesn't exist in your project but it is use in the file "gdisp_lld_framebuffer". Is there any components that I should integrate ?

Can you give me your file tree in order try in the same conditions as you ?

**Comment by InfiniteYuan** [comment]
Do you use git submodule command to fetch ugfx submodule?

**Comment by MamaTierra** [comment]
No I didn't ... It solve the problem. Thanks
